[HEADER]
Build-ID=22WW3OHFW02
CreatedBy=Kelly Lee
CreatedOn=12/13/2022 7:15:01 PM

[REQUIRED_DMI]

[FILESETS]
; P014A0-B2A = 22C2 Factory Update for OA3.trace for TPM Enhancement
Blk_1=P014A0-B2A
; P014BP-B2A = 23C1 Factory Update for Disable AppReadiness In AuditMode REG
Blk_2=P014BP-B2A

[INSTALL_SEQUENCE]
Blk_1=2
Blk_2=2

[CONDITIONS]

[DIB]
Blk_1=P014A0-B2A
Blk_2=P014BP-B2A

[RCD_ONLY]

[COMPONENTS]
Blk_1=22C2 Factory Update for OA3.trace for TPM Enhancement
Blk_2=23C1 Factory Update for Disable AppReadiness In AuditMode REG

[Version]
Blk_1=1.00
Blk_2=1.00

[Option_Map]

[RegionMap]
00=ABA
01=ABG
02=ABB
03=ABU
04=ABD
05=ABF
06=ABZ
07=ABE
13=AB9
14=AB8
15=AB7
16=ABM
17=ABV
20=AC4
21=AKC
24=AKD
25=ACB
26=AKS
27=AKE
28=AKL
29=ABJ
33=ABH
37=UUF
39=ACF
A4=UUG
A5=B10
AA=AB2
AB=AB0
AC=AB5
AD=AB1
AF=AB4
AR=ACQ
BB=ABT
BD=A2Q
BG=UUZ
BW=AR6
CP=AH3
CR=UUQ
D0=AC8
D1=AKH
D6=ACJ
DB=ABL
DE=AB6
DH=UUW
DL=A2N
DM=ACH
DT=B1R
E3=AKQ
F8=BED
FL=BCM
FM=BH4
FN=BH5

