# Generated by Django 5.2.4 on 2025-12-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=255)),
                ('local_body_type', models.CharField(max_length=100)),
                ('local_body_name', models.CharField(max_length=255)),
            ],
        ),
    ]
