# Generated by Django 5.2.4 on 2026-01-07 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousSymptomReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_disease', models.CharField(max_length=100)),
                ('confidence_score', models.FloatField()),
                ('symptoms_list', models.TextField()),
                ('symptoms_extracted_by_nlp', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('specific_address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('local_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports_api.localbody')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='risk_images/')),
                ('risk_type', models.CharField(max_length=100)),
                ('ai_detected_label', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('location_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('local_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports_api.localbody')),
            ],
        ),
        migrations.CreateModel(
            name='OfficialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('assigned_local_body', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports_api.localbody')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OutbreakAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('disease', models.CharField(max_length=100)),
                ('case_count', models.IntegerField(default=1)),
                ('status', models.CharField(default='WARNING', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('local_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports_api.localbody')),
            ],
        ),
    ]
