# Generated by Django 5.2.4 on 2026-01-10 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_api', '0002_anonymoussymptomreport_communityrisk_officialprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymoussymptomreport',
            name='internal_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='symptom_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='anonymoussymptomreport',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='officialprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='official_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
