# Generated by Django 5.2.4 on 2026-01-11 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_api', '0003_anonymoussymptomreport_internal_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymoussymptomreport',
            name='is_alerted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communityrisk',
            name='internal_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outbreakalert',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outbreakalert',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
