# Generated by Django 5.2.4 on 2026-01-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_api', '0004_anonymoussymptomreport_is_alerted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymoussymptomreport',
            name='symptoms_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
