# Generated by Django 5.2.4 on 2026-01-27 11:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_api', '0005_alter_anonymoussymptomreport_symptoms_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialprofile',
            name='last_report_check',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
