# Generated by Django 5.2.4 on 2026-01-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_api', '0006_officialprofile_last_report_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='localbody',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='localbody',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
