# Generated by Django 5.2.4 on 2026-03-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_api', '0007_localbody_latitude_localbody_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymoussymptomreport',
            name='model_weights_update',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
