[HEADER]
Build-ID=22WW3OHZ601
CreatedBy=Kelly Lee
CreatedOn=8/11/2022 7:34:23 PM

[REQUIRED_DMI]
Option1=PN.

[FILESETS]
; XSM22CS2BVT6AW = ML - Desktop - Consumer / 2018 / CoreML_cDT - CoreML_cDT (22C1) / 22CS2BVT6##
Blk_1=XSM22CS2BVT6AW
; XSM22CS2BGT6AS = ML - Notebook - Consumer / 2017 / XSM - CoreML (22C2) / 22CS2BGT6##
Blk_2=XSM22CS2BGT6AS
; XSM22CS2OFT6AJ = ML - Notebook - Consumer / 2017 / XSM - CoreML (22C2) / 22CS2OFT6##
Blk_3=XSM22CS2OFT6AJ
; XSM22CS2S2T6AQ = ML - Notebook - Consumer / 2017 / XSM - CoreML (22C2) / 22CS2S2T6##
Blk_4=XSM22CS2S2T6AQ
; XSM22CSV2PT6AT = ML - Notebook - Consumer / 2017 / XSM - CoreML (22C2) / 22CSV2PT6##
Blk_5=XSM22CSV2PT6AT
; P011ZJ-B2C = HP Documentation 2026
Blk_6=P011ZJ-B2C
; P011VM-B2B = OPI - Image Tweaks for Windows
Blk_7=P011VM-B2B
; P00WSS-B2A = Option Code Support Condition - CPS
Blk_8=P00WSS-B2A
; P00UA3-B2A = Windows 10 HP Driver Reinstallation Support - CPS
Blk_9=P00UA3-B2A
; P0104D-B2T = Alexa on Windows UWP
Blk_10=P0104D-B2T
; P010S0-B2E = E-QR Code - UWP
Blk_11=P010S0-B2E
; P00U8A-B2R = HP CoolSense UWP
Blk_12=P00U8A-B2R
; P013GW-B2B = Mediatek Bluetooth Driver for Microsoft Windows 10 - DCHU
Blk_13=P013GW-B2B
; P012MU-B2F = Mediatek WIFI Driver for Microsoft Windows 10 - DCHU
Blk_14=P012MU-B2F
; P0139R-B2M = myHP
Blk_15=P0139R-B2M
; P011YW-B2X = OPI 1.x - AMD High-Definition Graphics Driver
Blk_16=P011YW-B2X
; P011YE-B2H = OPI 1.x - ELAN Precision Touchpad Filter Driver
Blk_17=P011YE-B2H
; P011ZC-B2P = OPI 1.x - Nvidia Graphics Driver
Blk_18=P011ZC-B2P
; P011ZL-B2D = OPI 1.x - Realtek Card Reader Driver
Blk_19=P011ZL-B2D
; P011ZH-B2Z = OPI 1.x - Realtek High-Definition (HD) Audio Driver
Blk_20=P011ZH-B2Z
; P011YG-B2D = OPI 1.x - Realtek Local Area Network (LAN) Driver
Blk_21=P011YG-B2D

[INSTALL_SEQUENCE]
Blk_1=0
Blk_2=0
Blk_3=0
Blk_4=0
Blk_5=0
Blk_6=1
Blk_7=1
Blk_8=1
Blk_9=1
Blk_10=2
Blk_11=2
Blk_12=2
Blk_13=2
Blk_14=2
Blk_15=2
Blk_16=2
Blk_17=2
Blk_18=2
Blk_19=2
Blk_20=2
Blk_21=2

[CONDITIONS]
Blk_10_1=PN.ABA,R_FAPPS
Blk_10_2=PN.ABD,R_FAPPS
Blk_10_3=PN.ABE,R_FAPPS
Blk_10_4=PN.ABF,R_FAPPS
Blk_10_5=PN.ABG,R_FAPPS
Blk_10_6=PN.ABJ,R_FAPPS
Blk_10_7=PN.ABL,R_FAPPS
Blk_10_8=PN.ABU,R_FAPPS
Blk_10_9=PN.ABZ,R_FAPPS
Blk_10_10=PN.ACF,R_FAPPS
Blk_10_11=PN.ACJ,R_FAPPS

Blk_11_1=PN.AB2

Blk_13_1=USB\VID_0489&PID_E0E0&MI_00
Blk_13_2=USB\VID_0489&PID_E0E0&REV_0100&MI_00
Blk_13_3=USB\VID_0489&PID_E0F2&MI_00
Blk_13_4=USB\VID_0489&PID_E0F2&REV_0100&MI_00
Blk_13_5=USB\VID_0E8D&PID_1EDE&MI_00
Blk_13_6=USB\VID_0E8D&PID_1EDE&REV_0100&MI_00
Blk_13_7=USB\VID_13D3&PID_3567&MI_00
Blk_13_8=USB\VID_13D3&PID_3567&REV_0100&MI_00

Blk_14_1=PCI\VEN_14C3&DEV_0616&CC_0280
Blk_14_2=PCI\VEN_14C3&DEV_0616&CC_028000
Blk_14_3=PCI\VEN_14C3&DEV_0616&SUBSYS_E0CB105B
Blk_14_4=PCI\VEN_14C3&DEV_0616&SUBSYS_E0CB105B&REV_00
Blk_14_5=PCI\VEN_14C3&DEV_0616&SUBSYS_E0DB105B
Blk_14_6=PCI\VEN_14C3&DEV_0616&SUBSYS_E0DB105B&REV_00
Blk_14_7=PCI\VEN_14C3&DEV_7902&CC_0280
Blk_14_8=PCI\VEN_14C3&DEV_7902&CC_028000
Blk_14_9=PCI\VEN_14C3&DEV_7902&SUBSYS_1EDE14C3
Blk_14_10=PCI\VEN_14C3&DEV_7902&SUBSYS_1EDE14C3&REV_00
Blk_14_11=PCI\VEN_14C3&DEV_7961&CC_0280
Blk_14_12=PCI\VEN_14C3&DEV_7961&CC_028000
Blk_14_13=PCI\VEN_14C3&DEV_7961&SUBSYS_46821A3B
Blk_14_14=PCI\VEN_14C3&DEV_7961&SUBSYS_46821A3B&REV_00

Blk_15_1=R_STD
Blk_15_2=R_VR

Blk_16_1=PCI\VEN_1002&DEV_1638&SUBSYS_8A3C103C
Blk_16_2=PCI\VEN_1002&DEV_1638&SUBSYS_8A3D103C
Blk_16_3=PCI\VEN_1002&DEV_1638&SUBSYS_8A3E103C
Blk_16_4=PCI\VEN_1002&DEV_1638&SUBSYS_8A3F103C
Blk_16_5=PCI\VEN_1002&DEV_7437&SUBSYS_8A3F103C

Blk_17_1=HID\ELAN0787&Col01
Blk_17_2=HID\ELAN0787&Col02
Blk_17_3=HID\ELAN0787&Col03
Blk_17_4=HID\VEN_ELAN&DEV_0787&Col01
Blk_17_5=HID\VEN_ELAN&DEV_0787&Col02
Blk_17_6=HID\VEN_ELAN&DEV_0787&Col03

Blk_18_1=PCI\VEN_10DE&DEV_1F9D&SUBSYS_8A3E103C
Blk_18_2=PCI\VEN_10DE&DEV_25A0&SUBSYS_8A3C103C
Blk_18_3=PCI\VEN_10DE&DEV_25A2&SUBSYS_8A3D103C

Blk_19_1=PCI\VEN_10EC&DEV_5228&SUBSYS_8A3C103C
Blk_19_2=PCI\VEN_10EC&DEV_5228&SUBSYS_8A3D103C
Blk_19_3=PCI\VEN_10EC&DEV_5228&SUBSYS_8A3E103C
Blk_19_4=PCI\VEN_10EC&DEV_5228&SUBSYS_8A3F103C

Blk_20_1=HDAUDIO\FUNC_01&VEN_10EC&DEV_0245&SUBSYS_103C8A3C
Blk_20_2=HDAUDIO\FUNC_01&VEN_10EC&DEV_0245&SUBSYS_103C8A3D
Blk_20_3=HDAUDIO\FUNC_01&VEN_10EC&DEV_0245&SUBSYS_103C8A3E
Blk_20_4=HDAUDIO\FUNC_01&VEN_10EC&DEV_0245&SUBSYS_103C8A3F

Blk_21_1=PCI\VEN_10EC&DEV_8168
Blk_21_2=PCI\VEN_10EC&DEV_8168&SUBSYS_8A3C103C
Blk_21_3=PCI\VEN_10EC&DEV_8168&SUBSYS_8A3D103C
Blk_21_4=PCI\VEN_10EC&DEV_8168&SUBSYS_8A3E103C
Blk_21_5=PCI\VEN_10EC&DEV_8168&SUBSYS_8A3F103C


[DIB]
Blk_4=XSM22CS2S2T6AQ
Blk_5=XSM22CSV2PT6AT
Blk_6=P011ZJ-B2C
Blk_7=P011VM-B2B
Blk_9=P00UA3-B2A
Blk_10=P0104D-B2T
Blk_11=P010S0-B2E
Blk_12=P00U8A-B2R
Blk_13=P013GW-B2B
Blk_14=P012MU-B2F
Blk_15=P0139R-B2M
Blk_16=P011YW-B2X
Blk_17=P011YE-B2H
Blk_18=P011ZC-B2P
Blk_19=P011ZL-B2D
Blk_20=P011ZH-B2Z
Blk_21=P011YG-B2D

[RCD_ONLY]

[COMPONENTS]
Blk_1=ML - Desktop - Consumer / 2018 / CoreML_cDT - CoreML_cDT (22C1) / 22CS2BVT6##
Blk_2=ML - Notebook - Consumer / 2017 / XSM - CoreML (22C2) / 22CS2BGT6##
Blk_3=ML - Notebook - Consumer / 2017 / XSM - CoreML (22C2) / 22CS2OFT6##
Blk_4=ML - Notebook - Consumer / 2017 / XSM - CoreML (22C2) / 22CS2S2T6##
Blk_5=ML - Notebook - Consumer / 2017 / XSM - CoreML (22C2) / 22CSV2PT6##
Blk_6=HP Documentation 2026
Blk_7=OPI - Image Tweaks for Windows
Blk_8=Option Code Support Condition - CPS
Blk_9=Windows 10 HP Driver Reinstallation Support - CPS
Blk_10=Alexa on Windows UWP
Blk_11=E-QR Code - UWP
Blk_12=HP CoolSense UWP
Blk_13=Mediatek Bluetooth Driver for Microsoft Windows 10 - DCHU
Blk_14=Mediatek WIFI Driver for Microsoft Windows 10 - DCHU
Blk_15=myHP
Blk_16=OPI 1.x - AMD High-Definition Graphics Driver
Blk_17=OPI 1.x - ELAN Precision Touchpad Filter Driver
Blk_18=OPI 1.x - Nvidia Graphics Driver
Blk_19=OPI 1.x - Realtek Card Reader Driver
Blk_20=OPI 1.x - Realtek High-Definition (HD) Audio Driver
Blk_21=OPI 1.x - Realtek Local Area Network (LAN) Driver

[Version]
Blk_1=22CS2BVT6AW
Blk_2=22CS2BGT6AS
Blk_3=22CS2OFT6AJ
Blk_4=22CS2S2T6AQ
Blk_5=22CSV2PT6AT
Blk_6=1.01
Blk_7=22C2
Blk_8=1.00
Blk_9=1.1820
Blk_10=3.24.1213.0
Blk_11=1.0.16.0
Blk_12=1.1.3.0
Blk_13=2.22.0.2
Blk_14=3.5.0.2
Blk_15=8.52229.257.0
Blk_16=31.0.12002.4002
Blk_17=22.2.30.3
Blk_18=30.0.15.1278
Blk_19=10.0.22621.21357
Blk_20=6.0.9381.1
Blk_21=1168.8.515.2022

[Option_Map]
bh=R_STD
ez=R_VR
m9=R_FAPPS

[RegionMap]
00=ABA
01=ABG
02=ABB
03=ABU
04=ABD
05=ABF
06=ABZ
07=ABE
13=AB9
14=AB8
15=AB7
16=ABM
17=ABV
20=AC4
21=AKC
24=AKD
25=ACB
26=AKS
27=AKE
28=AKL
29=ABJ
33=ABH
37=UUF
39=ACF
A4=UUG
A5=B10
AA=AB2
AB=AB0
AC=AB5
AD=AB1
AF=AB4
AR=ACQ
BB=ABT
BD=A2Q
BG=UUZ
BW=AR6
CP=AH3
CR=UUQ
D0=AC8
D1=AKH
D6=ACJ
DB=ABL
DE=AB6
DH=UUW
DL=A2N
DM=ACH
DT=B1R
E3=AKQ
F8=BED
FL=BCM
FM=BH4
FN=BH5

