; Added info from [C:\HP\SUPPORT\ML.ini] file.

[PN_DELIV]
XSM22CS2BVT6AW=ML - Desktop - Consumer / 2018 / CoreML_cDT - CoreML_cDT (22C1) / 22CS2BVT6##
XSM22CS2BGT6AS=ML - Notebook - Consumer / 2017 / XSM - CoreML (22C2) / 22CS2BGT6##
XSM22CS2OFT6AJ=ML - Notebook - Consumer / 2017 / XSM - CoreML (22C2) / 22CS2OFT6##
XSM22CS2S2T6AQ=ML - Notebook - Consumer / 2017 / XSM - CoreML (22C2) / 22CS2S2T6##
XSM22CSV2PT6AT=ML - Notebook - Consumer / 2017 / XSM - CoreML (22C2) / 22CSV2PT6##
P011ZJ-B2C=HP Documentation 2026
P011VM-B2B=OPI - Image Tweaks for Windows
P00WSS-B2A=Option Code Support Condition - CPS
P00UA3-B2A=Windows 10 HP Driver Reinstallation Support - CPS
P0104D-B2T=Alexa on Windows UWP
P010S0-B2E=E-QR Code - UWP
P00U8A-B2R=HP CoolSense UWP
P013GW-B2B=Mediatek Bluetooth Driver for Microsoft Windows 10 - DCHU
P012MU-B2F=Mediatek WIFI Driver for Microsoft Windows 10 - DCHU
P0139R-B2M=myHP
P011YW-B2X=OPI 1.x - AMD High-Definition Graphics Driver
P011YE-B2H=OPI 1.x - ELAN Precision Touchpad Filter Driver
P011ZC-B2P=OPI 1.x - Nvidia Graphics Driver
P011ZL-B2D=OPI 1.x - Realtek Card Reader Driver
P011ZH-B2Z=OPI 1.x - Realtek High-Definition (HD) Audio Driver
P011YG-B2D=OPI 1.x - Realtek Local Area Network (LAN) Driver
; Added info from [c:\hp\support\XSM22CS2BGT6AS.ini] file.

P00RRP-B2X=HP Connection Optimizer
P00YHR-B2K=HP Support Assistant
P00S1R-B2L=Energy Star UWP
P00YDT-B2Q=HP OMEN Fusion Driver
P012NB-B2E=HP PC Hardware Diagnostics UEFI
P00YTQ-B2K=HP PC Hardware Diagnostics Windows
P012T2-B2P=HP System Event Utility - UWP
P012FF-B2S=OMEN Command Center - UWP
P0114T-B2V=SDK Pack for OMEN Command Center
P00WVG-B2V=sMedio True DVD for HP
; Added info from [c:\hp\support\XSM22CS2BVT6AW.ini] file.

P00Y91-B2B=Bing Search for IE11
P011DS-B2G=Retail Demo - Video Attract Loop
P01258-B2U=Touchpoint Customizer for Consumer
P0132P-B2F=WW-BTB Host and ISP Stub
P00YH0-B2T=Adobe Offer
P011J8-B2C=Agoda Edge Fav
P011J7-B2D=Agoda URL
P00ZRH-B2P=Amazon URL offers
P010DQ-B2F=Amazon URL offers CMIT
P0129P-B2N=Baidu Netdisk
P00ZLN-B2H=Baidu Search
P00Y70-B2K=Booking Edge Fav
P00UTX-B2U=Booking URL
P0100R-B2R=Concepts
P00ZEG-B2S=Dropbox Promotion
P012FW-B2K=Duet for HP
P00ZZF-B2K=Express VPN
P00Y8G-B2P=ExpressVPN Edge Favorites
P00S93-B2K=FileBackup_UWP
P00W3X-B2W=HP e-Service
P00ZKU-B2L=HP Favorite for China
P012CM-B2A=HP Privacy Settings
P0136B-B2A=HP QuickDrop
P012B1-B2B=HP Setup Integrated OOBE (GDPR)
P00Z6V-B2N=HP Smart
P012YT-B2F=HSA Fusion
P00ZAN-B2U=HSA Telemetry for Consumer
P012Z6-B2A=LastPass Edge Favorites
P0107M-B2G=LastPass password manager
P0106S-B2K=Magic Desktop Premium by EasyBits
P00Z10-B2Y=McAfee - MLS
P00U1P-B2W=McAfee LiveSafe Install Rules Configuration
P010UD-B2H=McAfee URL
P010KU-B2K=MYOffice
P00YGD-B2V=Retail Demo - Get Started App (GSA)
P00YKE-B2P=Russian regulation offer
P00ZRX-B2L=Simple Solitaire-Metro
P011VC-B2L=TianYi Cloud
P00VSE-B2U=Walmart Shopping
P00XM6-B2V=WPS Office
P00ZK7-B2X=WPS Office CMIT
P011TY-B2D=WT Games for HP-Brazil
P00YYD-B2Q=WT Games for HP-Europe
P011TZ-B2D=WT Games for HP-Korea
P010EC-B2P=WT Games for HP-LITE
P00Z8B-B2Q=WT Games for HP-ROW
P0131N-B2B=WT Games for HP-US
P00ZHX-B2L=Yandex Browser
; Added info from [c:\hp\support\XSM22CS2OFT6AJ.ini] file.

P012RS-B2H=Microsoft Office OPK
P012RN-00E=Microsoft Office OPK - Language Packs
P012RN-03E=Microsoft Office OPK - Language Packs
P012RN-04E=Microsoft Office OPK - Language Packs
P012RN-05E=Microsoft Office OPK - Language Packs
P012RN-06E=Microsoft Office OPK - Language Packs
P012RN-07E=Microsoft Office OPK - Language Packs
P012RN-08E=Microsoft Office OPK - Language Packs
P012RN-09E=Microsoft Office OPK - Language Packs
P012RN-10E=Microsoft Office OPK - Language Packs
P012RN-12E=Microsoft Office OPK - Language Packs
P012RN-13E=Microsoft Office OPK - Language Packs
P012RN-14E=Microsoft Office OPK - Language Packs
P012RN-15E=Microsoft Office OPK - Language Packs
P012RN-16E=Microsoft Office OPK - Language Packs
P012RN-17E=Microsoft Office OPK - Language Packs
P012RN-20E=Microsoft Office OPK - Language Packs
P012RN-21E=Microsoft Office OPK - Language Packs
P012RN-22E=Microsoft Office OPK - Language Packs
P012RN-23E=Microsoft Office OPK - Language Packs
P012RN-24E=Microsoft Office OPK - Language Packs
P012RN-25E=Microsoft Office OPK - Language Packs
P012RN-26E=Microsoft Office OPK - Language Packs
P012RN-27E=Microsoft Office OPK - Language Packs
P012RN-28E=Microsoft Office OPK - Language Packs
P012RN-29E=Microsoft Office OPK - Language Packs
P012RN-33E=Microsoft Office OPK - Language Packs
P012RN-35E=Microsoft Office OPK - Language Packs
P012RN-AAE=Microsoft Office OPK - Language Packs
P012RN-ABE=Microsoft Office OPK - Language Packs
P012RN-ADE=Microsoft Office OPK - Language Packs
P012RN-BAE=Microsoft Office OPK - Language Packs
P012RN-BBE=Microsoft Office OPK - Language Packs
P012RN-BCE=Microsoft Office OPK - Language Packs
P012RN-BDE=Microsoft Office OPK - Language Packs
P012RN-E1E=Microsoft Office OPK - Language Packs
P012RN-E2E=Microsoft Office OPK - Language Packs
P012RN-E3E=Microsoft Office OPK - Language Packs
P012RN-E4E=Microsoft Office OPK - Language Packs
; Added info from [c:\hp\support\XSM22CS2S2T6AQ.ini] file.

P010C1-B2J=MS Windows DPK ReG - CPS
P00YAV-B2J=Windows 10 PCIE Root Port Constraints - CPS
P00YYE-B2H=Windows 10 RedStone HP EULA - CPS
P00QL5-B2R=Windows 10 RedStone Regional Settings Flag - CPS
P00V0F-B2Q=Windows 10 System Default Power Settings - CPS
P010VE-B2M=Windows 10 Wallpaper - CPS
P012NJ-B2K=Windows 11 22H2 Base Image CH SL 64 Bit - CPS
P012NH-B2K=Windows 11 22H2 Base Image SL 64 Bit - CPS
P01351-B2C=Windows 11 22H2 GDR 64bit - CPS
P012J6-B2N=Windows 11 22H2 Language Interface Package 64 Bit - CPS
P012J5-00N=Windows 11 22H2 Language Pack 64 Bit - CPS
P012J5-03N=Windows 11 22H2 Language Pack 64 Bit - CPS
P012J5-04N=Windows 11 22H2 Language Pack 64 Bit - CPS
P012J5-05N=Windows 11 22H2 Language Pack 64 Bit - CPS
P012J5-06N=Windows 11 22H2 Language Pack 64 Bit - CPS
P012J5-07N=Windows 11 22H2 Language Pack 64 Bit - CPS
P012J5-08N=Windows 11 22H2 Language Pack 64 Bit - CPS
P012J5-09N=Windows 11 22H2 Language Pack 64 Bit - CPS
P012J5-10N=Windows 11 22H2 Language Pack 64 Bit - CPS
P012J5-12N=Windows 11 22H2 Language Pack 64 Bit - CPS
P012J5-13N=Windows 11 22H2 Language Pack 64 Bit - CPS
P012J5-14N=Windows 11 22H2 Language Pack 64 Bit - CPS
P012J5-15N=Windows 11 22H2 Language Pack 64 Bit - CPS
P012J5-16N=Windows 11 22H2 Language Pack 64 Bit - CPS
P012J5-17N=Windows 11 22H2 Language Pack 64 Bit - CPS
P012J5-20N=Windows 11 22H2 Language Pack 64 Bit - CPS
P012J5-21N=Windows 11 22H2 Language Pack 64 Bit - CPS
P012J5-22N=Windows 11 22H2 Language Pack 64 Bit - CPS
P012J5-23N=Windows 11 22H2 Language Pack 64 Bit - CPS
P012J5-24N=Windows 11 22H2 Language Pack 64 Bit - CPS
P012J5-25N=Windows 11 22H2 Language Pack 64 Bit - CPS
P012J5-26N=Windows 11 22H2 Language Pack 64 Bit - CPS
P012J5-27N=Windows 11 22H2 Language Pack 64 Bit - CPS
P012J5-28N=Windows 11 22H2 Language Pack 64 Bit - CPS
P012J5-29N=Windows 11 22H2 Language Pack 64 Bit - CPS
P012J5-33N=Windows 11 22H2 Language Pack 64 Bit - CPS
P012J5-35N=Windows 11 22H2 Language Pack 64 Bit - CPS
P012J5-AAN=Windows 11 22H2 Language Pack 64 Bit - CPS
P012J5-ABN=Windows 11 22H2 Language Pack 64 Bit - CPS
P012J5-ACN=Windows 11 22H2 Language Pack 64 Bit - CPS
P012J5-ADN=Windows 11 22H2 Language Pack 64 Bit - CPS
P012J5-BAN=Windows 11 22H2 Language Pack 64 Bit - CPS
P012J5-BBN=Windows 11 22H2 Language Pack 64 Bit - CPS
P012J5-BCN=Windows 11 22H2 Language Pack 64 Bit - CPS
P012J5-BDN=Windows 11 22H2 Language Pack 64 Bit - CPS
P012J5-E1N=Windows 11 22H2 Language Pack 64 Bit - CPS
P012J5-E2N=Windows 11 22H2 Language Pack 64 Bit - CPS
P012J5-E3N=Windows 11 22H2 Language Pack 64 Bit - CPS
P012J5-E4N=Windows 11 22H2 Language Pack 64 Bit - CPS
P012J7-B2N=Windows 11 22H2 LP FOD Supplement - CPS
P012J9-B2P=Windows 11 22H2 MS Codec Resources - CPS
P012J8-B2P=Windows 11 22H2 MS Start App Resources - CPS
P012JC-B2N=Windows 11 22H2 OA3Tool File ONLY - CPS
P012JD-B2N=Windows 11 22H2 OA3Tool Hook - CPS
P012NG-B2J=Windows 11 22H2 WinPE - CPS
P012PZ-B2C=Windows 11 HP OS Enhancement - CPS
; Added info from [c:\hp\support\XSM22CSV2PT6AT.ini] file.

P00V2E-B2A=BCU Utility and Configure File - CPS
P011YS-B2D=DMIFIT Data Configuration - CPS
P012L1-B2B=DPS tweaks ReG V2 - CPS
P00PS9-B2D=Dump BCU before and after downloading customer image Hook - CPS
P00NQ0-B2C=Dump BTO and CMD after MD5 Hook - CPS
P00W2W-B2H=Dynamic MSC - CPS
P001FT-B2H=Flag - HWI_GMPP Capable Image
P00WST-B2F=GBUHook for Option Code Support Condition Check - CPS
P00X8R-B2B=GBUHook Inject WinPE Driver - CPS
P00VM5-B2K=GBUHook support Drive Order change
P00VM6-B2C=GBUHook support PML share mode - CPS
P00YTV-B2B=GBUHook to collect Server Driver Support Readiness - CPS
P00TB1-B2N=HP BIOS ReadBack Utility (HPRB)-AMI
P00TBB-B2J=HP BIOS ReadBack Utility (HPRB)-Insyde
P00UT8-B2Q=HP Image Factory Update Framework - CPS
P0124K-B2B=HP Image McAfee 2PP Stay Moderation - CPS
P010PA-B2Q=HP Windows Image Diagnostic Tools - CPS
P012L9-B2D=HP WMI Console Utility - CalebWMI - CPS
P0104N-B2E=Image Pre-requirements Reset Hook - CPS
P00TKB-B2A=MPM Unlock support flag for Diags - CPS
P012C8-B2G=MS Windows PIN Process ReG V2 - CPS
P00LWZ-B2A=MSC - NTFS (26GB / 1.5GB)
P0119B-B2H=Preinstall Log Collector - CPS
P010UC-B2T=RStone Detection Tweaks - CPS
P00ZYA-B2M=Secure Boot Hook - CPS
P00Y6T-B2J=ShareData Update - CPS
P011LD-B2V=Unit Data Collector - CPS
P00WK8-B2D=WDT Hook - Log Image Version
P00Z75-B2F=Win Hook - CPS
P00Y06-B2C=Windows 10 COMPACT Recapture - CPS
P01069-B2A=Windows 10 HP Image Enhancements Addon SLCapture 0A3 - CPS
P00RYB-B2D=Windows 10 Image Customization for Microsoft Signature - CPS
P00P9Y-B2S=Windows 10 Image Customization Tweaks - CPS
P00NGN-B2B=Windows Big File Tweaks - CPS
P00KH9-B2J=Windows HP File Based Installer
P012MJ-B2G=Windows HP Image Enhancements - CPS
P011DF-B2A=Windows HP Image Enhancements Addon DDL Variable - CPS
P012MK-B2B=Windows Image Security Diagnostic - CPS
P00QSA-B2C=Windows OA3 Hook - CPS
P010UR-B2C=Windows October 2021 OOBE Presetting - CPS
P012LZ-B2D=Windows Push Button Reset Recovery - CPS
P011Y6-B2B=DisableSR - CPS
