[HEADER]
Build-ID=22CS2BGT6AS
CreatedBy=Vicky Kuo
CreatedOn=8/2/2022 1:01:21 AM

[REQUIRED_DMI]
Option1=SL.
Option2=PN.

[FILESETS]
; P00RRP-B2X = HP Connection Optimizer
Blk_1=P00RRP-B2X
; P00YHR-B2K = HP Support Assistant
Blk_2=P00YHR-B2K
; P00S1R-B2L = Energy Star UWP
Blk_3=P00S1R-B2L
; P00YDT-B2Q = HP OMEN Fusion Driver
Blk_4=P00YDT-B2Q
; P012NB-B2E = HP PC Hardware Diagnostics UEFI
Blk_5=P012NB-B2E
; P00YTQ-B2K = HP PC Hardware Diagnostics Windows
Blk_6=P00YTQ-B2K
; P012T2-B2P = HP System Event Utility - UWP
Blk_7=P012T2-B2P
; P012FF-B2S = OMEN Command Center - UWP
Blk_8=P012FF-B2S
; P0114T-B2V = SDK Pack for OMEN Command Center
Blk_9=P0114T-B2V
; P00WVG-B2V = sMedio True DVD for HP
Blk_10=P00WVG-B2V

[INSTALL_SEQUENCE]
Blk_1=1
Blk_2=1
Blk_3=2
Blk_4=2
Blk_5=2
Blk_6=2
Blk_7=2
Blk_8=2
Blk_9=2
Blk_10=2

[CONDITIONS]
Blk_1_1=R_MIC
Blk_1_2=R_STD

Blk_2_1=R_MIC
Blk_2_2=R_STD
Blk_2_3=R_VR

Blk_3_1=Estar

Blk_6_1=R_MIC
Blk_6_2=R_STD
Blk_6_3=R_VR

Blk_9_1=SL.GAM

Blk_10_1=PN.A2N,DVDr
Blk_10_2=PN.A2Q,DVDr
Blk_10_3=PN.AB0,DVDr
Blk_10_4=PN.AB1,DVDr
Blk_10_5=PN.AB4,DVDr
Blk_10_6=PN.AB5,DVDr
Blk_10_7=PN.AB6,DVDr
Blk_10_8=PN.AB7,DVDr
Blk_10_9=PN.AB8,DVDr
Blk_10_10=PN.AB9,DVDr
Blk_10_11=PN.ABA,DVDr
Blk_10_12=PN.ABB,DVDr
Blk_10_13=PN.ABD,DVDr
Blk_10_14=PN.ABE,DVDr
Blk_10_15=PN.ABF,DVDr
Blk_10_16=PN.ABG,DVDr
Blk_10_17=PN.ABH,DVDr
Blk_10_18=PN.ABJ,DVDr
Blk_10_19=PN.ABL,DVDr
Blk_10_20=PN.ABM,DVDr
Blk_10_21=PN.ABT,DVDr
Blk_10_22=PN.ABU,DVDr
Blk_10_23=PN.ABV,DVDr
Blk_10_24=PN.ABZ,DVDr
Blk_10_25=PN.AC4,DVDr
Blk_10_26=PN.AC8,DVDr
Blk_10_27=PN.ACB,DVDr
Blk_10_28=PN.ACF,DVDr
Blk_10_29=PN.ACH,DVDr
Blk_10_30=PN.ACJ,DVDr
Blk_10_31=PN.ACQ,DVDr
Blk_10_32=PN.AH3,DVDr
Blk_10_33=PN.AK4,DVDr
Blk_10_34=PN.AKC,DVDr
Blk_10_35=PN.AKD,DVDr
Blk_10_36=PN.AKE,DVDr
Blk_10_37=PN.AKH,DVDr
Blk_10_38=PN.AKL,DVDr
Blk_10_39=PN.AKQ,DVDr
Blk_10_40=PN.AKS,DVDr
Blk_10_41=PN.AR6,DVDr
Blk_10_42=PN.B10,DVDr
Blk_10_43=PN.B1R,DVDr
Blk_10_44=PN.BCM,DVDr
Blk_10_45=PN.BED,DVDr
Blk_10_46=PN.BH4,DVDr
Blk_10_47=PN.BH5,DVDr
Blk_10_48=PN.BJA,DVDr
Blk_10_49=PN.UUF,DVDr
Blk_10_50=PN.UUG,DVDr
Blk_10_51=PN.UUQ,DVDr
Blk_10_52=PN.UUW,DVDr
Blk_10_53=PN.UUZ,DVDr
Blk_10_54=PN.A2N,DVDRW
Blk_10_55=PN.A2Q,DVDRW
Blk_10_56=PN.AB0,DVDRW
Blk_10_57=PN.AB1,DVDRW
Blk_10_58=PN.AB4,DVDRW
Blk_10_59=PN.AB5,DVDRW
Blk_10_60=PN.AB6,DVDRW
Blk_10_61=PN.AB7,DVDRW
Blk_10_62=PN.AB8,DVDRW
Blk_10_63=PN.AB9,DVDRW
Blk_10_64=PN.ABA,DVDRW
Blk_10_65=PN.ABB,DVDRW
Blk_10_66=PN.ABD,DVDRW
Blk_10_67=PN.ABE,DVDRW
Blk_10_68=PN.ABF,DVDRW
Blk_10_69=PN.ABG,DVDRW
Blk_10_70=PN.ABH,DVDRW
Blk_10_71=PN.ABJ,DVDRW
Blk_10_72=PN.ABL,DVDRW
Blk_10_73=PN.ABM,DVDRW
Blk_10_74=PN.ABT,DVDRW
Blk_10_75=PN.ABU,DVDRW
Blk_10_76=PN.ABV,DVDRW
Blk_10_77=PN.ABZ,DVDRW
Blk_10_78=PN.AC4,DVDRW
Blk_10_79=PN.AC8,DVDRW
Blk_10_80=PN.ACB,DVDRW
Blk_10_81=PN.ACF,DVDRW
Blk_10_82=PN.ACH,DVDRW
Blk_10_83=PN.ACJ,DVDRW
Blk_10_84=PN.ACQ,DVDRW
Blk_10_85=PN.AH3,DVDRW
Blk_10_86=PN.AK4,DVDRW
Blk_10_87=PN.AKC,DVDRW
Blk_10_88=PN.AKD,DVDRW
Blk_10_89=PN.AKE,DVDRW
Blk_10_90=PN.AKH,DVDRW
Blk_10_91=PN.AKL,DVDRW
Blk_10_92=PN.AKQ,DVDRW
Blk_10_93=PN.AKS,DVDRW
Blk_10_94=PN.AR6,DVDRW
Blk_10_95=PN.B10,DVDRW
Blk_10_96=PN.B1R,DVDRW
Blk_10_97=PN.BCM,DVDRW
Blk_10_98=PN.BED,DVDRW
Blk_10_99=PN.BH4,DVDRW
Blk_10_100=PN.BH5,DVDRW
Blk_10_101=PN.BJA,DVDRW
Blk_10_102=PN.UUF,DVDRW
Blk_10_103=PN.UUG,DVDRW
Blk_10_104=PN.UUQ,DVDRW
Blk_10_105=PN.UUW,DVDRW
Blk_10_106=PN.UUZ,DVDRW


[DIB]
Blk_5=P012NB-B2E
Blk_8=P012FF-B2S

[RCD_ONLY]

[COMPONENTS]
Blk_1=HP Connection Optimizer
Blk_2=HP Support Assistant
Blk_3=Energy Star UWP
Blk_4=HP OMEN Fusion Driver
Blk_5=HP PC Hardware Diagnostics UEFI
Blk_6=HP PC Hardware Diagnostics Windows
Blk_7=HP System Event Utility - UWP
Blk_8=OMEN Command Center - UWP
Blk_9=SDK Pack for OMEN Command Center
Blk_10=sMedio True DVD for HP

[Version]
Blk_1=2.0.19.0
Blk_2=9.12.43.0
Blk_3=100.00
Blk_4=1.0.800.0
Blk_5=8.7.1.0
Blk_6=1.8.1.0
Blk_7=1.3.2
Blk_8=1101.2207.6.0
Blk_9=1.0.63
Blk_10=1.1.155.0

[Option_Map]
3P=DVDr
3Q=DVDRW
aB=Estar
bg=R_MIC
bh=R_STD
ez=R_VR
fd=SL.GAM

[RegionMap]

